# Generated by Django 2.0.3 on 2018-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='deadline',
            field=models.CharField(max_length=255),
        ),
    ]
