# Generated by Django 2.0.3 on 2018-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180325_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='action_date',
            field=models.CharField(max_length=255),
        ),
    ]
